/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Composite

fun main(args: Array<String>) {


}

class Directory(val name: String) {
    var childs = listOf<Directory>()

    fun add(dir: Directory) {
        val copy = childs.toMutableList().apply {
            add(dir)
        }
        childs = copy
    }

    fun printDir(parentsDir: String) {

        print("$parentsDir/$name\n")

        if (childs.isNotEmpty()) {
            childs.map {
                it.printDir("$parentsDir/$name")
            }
        }
    }
}
